### ISSUE TITLE
Variant queries using HGVS

### ISSUE THREAD

**Issue by DavidCroftDKFZ** [EGA-archive/beacon2-ri-api#175]
Hi,

I would like to run a query against the g_variants endpoint with a filter that specifies the HGVS for a given variant, is that possible?

I think that putting non-alphanumeric characters into filters could be probelemmatic, so I guess I might need to use a modified notation.

In the CINECA dataset, the following is available:

  "variantInternalId": "chr22_16050075_A_G",

Could I use this for filtering? If so, what would the filter JSON look like?

Regards,

David Croft.

**Comment by costero-e** [comment]
Hi David,

yes, everything that is in the document can be queryable.

The "variantInternalId" field for the g_variants endpoint is considered as the "id" of every document in this collection, so you just need to  do a query of the type `g_variants/{id}`

The GET request tested locally should look like `http://localhost:5050/api/g_variants/chr22_16050527_C_A`

The POST request tested locally should look like `curl \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{
    "meta": {
        "apiVersion": "2.0"
    }
}' \
  http://localhost:5050/api/g_variants/chr22_16050075_A_G`

Remember that after that you can also add the request parameters you want to add to the query, like for example `http://localhost:5050/api/g_variants/chr22_16050527_C_A?variantType=SNP`

I hope this helps. If you have any other doubt, don't hesitate to ask.

Thank you!

Oriol López-Doriga

**Comment by DavidCroftDKFZ** [comment]
Hi,


Is there an equivalent JSON body that I can send to the g_variants endpoint run this filter (using POST)?


Regards,


David Croft-




________________________________
From: Oriol López-Doriga ***@***.***>
Sent: Wednesday, August 16, 2023 10:14 AM
To: EGA-archive/beacon2-ri-api
Cc: Croft, David; Author
Subject: [Extern] - Re: [EGA-archive/beacon2-ri-api] Variant queries using HGVS (Issue #175)


Hi David,

yes, everything that is in the document can be queryable.

The "variantInternalId" field for the g_variants endpoint is considered as the "id" of every document in this collection, so you just need to do a query of the type g_variants/{id}

The GET request tested locally should look like http://localhost:5050/api/g_variants/chr22_16050527_C_A

The POST request tested locally should look like curl \ -H 'Content-Type: application/json' \ -X POST \ -d '{ "meta": { "apiVersion": "2.0" } }' \ http://localhost:5050/api/g_variants/chr22_16050075_A_G

Remember that after that you can also add the request parameters you want to add to the query, like for example http://localhost:5050/api/g_variants/chr22_16050527_C_A?variantType=SNP

I hope this helps. If you have any other doubt, don't hesitate to ask.

Thank you!

Oriol López-Doriga

**Comment by costero-e** [comment]
Hi,
in the last message I wrote an example of a json body POST to use the "id". Let me write it again in block better:
```
curl \ 
-H 'Content-Type: application/json' \ 
-X POST \ 
-d '{ "meta": { "apiVersion": "2.0" } }' \ 
http://localhost:5050/api/g_variants/chr22_16050075_A_G
```

Does this help you? You just have to write the id in the URI requested.

Best,

Oriol

**Comment by DavidCroftDKFZ** [comment]
Hi,


Thanks for the example.


My understanding is that there are two ways to define filters. One is to insert IDs into the URL, as in your example. The other is to send JSON in the body, something like this:


POST: http://localhost:5050/api/individuals


BODY:


{
        "query": {
                "filters": [
                        {
                                "id": "NCIT:C20197"
                        }
                ],
                "includeResultsetResponses": "HIT",
                "testMode": false,
                "requestedGranularity": "count"
        }
}


The body contains a query block, which in turn contains a list of filters.


Can I do something like this with genetic variants, where the query is sent in the body as a filter term?


Regards,


David Croft.

________________________________
From: Oriol López-Doriga ***@***.***>
Sent: Wednesday, August 16, 2023 5:29 PM
To: EGA-archive/beacon2-ri-api
Cc: Croft, David; Author
Subject: [Extern] - Re: [EGA-archive/beacon2-ri-api] Variant queries using HGVS (Issue #175)


Hi,
in the last message I wrote an example of a json body POST to use the "id". Let me write it again in block better:

curl \
-H 'Content-Type: application/json' \
-X POST \
-d '{ "meta": { "apiVersion": "2.0" } }' \
http://localhost:5050/api/g_variants/chr22_16050075_A_G


Does this help you? You just have to write the id in the URI requested.

Best,

Oriol

**Comment by costero-e** [comment]
Hi David,

thank you for the explanation.

First of all, I have to tell you that Beacon specifications say that to search inside the g_variants endpoint you have to use request parameters other than filters, which are more used to find "clinical data", and the reason why ontologies are used. From this, then, alphanumeric and custom filters are used to find a "specific value" of this clinical data.

However, the "InternalVariantId" is not mapped for the request parameters because it is on purpose mapped in the specific /{id} endpoint,  so I am afraid the only way to look for the "InternalVariantId" is by specifying it in the requested URI. 
If you check the specifications here https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/framework/json/requests/examples-sections/requestParameters-example.json you will find the request parameters to be `All the required fields to query any kind of variant (e.g. SNP, DUP,\netc.)."`.

Nonetheless, you can still get to this "InternalVariantId" by passing the exact request parameters that match it, like doing this type of POST request:

```
curl \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{
    "meta": {
        "apiVersion": "2.0"
    },
    "query": {
        "requestParameters": {
"Chromosome": "22",
    "alternateBases": "G" ,
    "referenceBases": "A" ,
"start": [ 16050075 ],
            "end": [ 16050075 ],
	    "variantType": "SNP"
        },
        "filters": [],
        "includeResultsetResponses": "HIT",
        "pagination": {
            "skip": 0,
            "limit": 10
        },
        "testMode": false,
        "requestedGranularity": "record"
    }
}' \
  http://localhost:5050/api/g_variants
``` 
I hope this helps you.

Best,

Oriol

**Comment by DavidCroftDKFZ** [comment]
Hi Oriol,


That was very useful, thanks for the detailed reply!


Regards,


David.


________________________________
From: Oriol López-Doriga ***@***.***>
Sent: Thursday, August 17, 2023 4:28 PM
To: EGA-archive/beacon2-ri-api
Cc: Croft, David; Author
Subject: [Extern] - Re: [EGA-archive/beacon2-ri-api] Variant queries using HGVS (Issue #175)


Hi David,

thank you for the explanation.

First of all, I have to tell you that Beacon specifications say that to search inside the g_variants endpoint you have to use request parameters other than filters, which are more used to find "clinical data", and the reason why ontologies are used. From this, then, alphanumeric and custom filters are used to find a "specific value" of this clinical data.

However, the "InternalVariantId" is not mapped for the request parameters because it is on purpose mapped in the specific /{id} endpoint, so I am afraid the only way to look for the "InternalVariantId" is by specifying it in the requested URI.
If you check the specifications here https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/framework/json/requests/examples-sections/requestParameters-example.json you will find the request parameters to be All the required fields to query any kind of variant (e.g. SNP, DUP,\netc.).".

Nonetheless, you can still get to this "InternalVariantId" by passing the exact request parameters that match it, like doing this type of POST request:

curl \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{
    "meta": {
        "apiVersion": "2.0"
    },
    "query": {
        "requestParameters": {
"Chromosome": "22",
    "alternateBases": "G" ,
    "referenceBases": "A" ,
"start": [ 16050075 ],
            "end": [ 16050075 ],
            "variantType": "SNP"
        },
        "filters": [],
        "includeResultsetResponses": "HIT",
        "pagination": {
            "skip": 0,
            "limit": 10
        },
        "testMode": false,
        "requestedGranularity": "record"
    }
}' \
  http://localhost:5050/api/g_variants


I hope this helps you.

Best,

Oriol

**Comment by DavidCroftDKFZ** [comment]
Hi Oriol,


Thanks for the requestParameters example.


When I ran this, I got a 500 error and in the logs I could see that "Chromosome" causes an index error. I tried "chromosome" with the same result. If I remove the chromosome line altogether, the query runs but returns zero results.


I am using the Cineca test data set. Here is an example of what is in the genetic variants BFF file:


    "variantQuality": {
      "FILTER": "PASS",
      "QUAL": 100
    },
    "_position": {
      "start": [
        16050074
      ],
      "end": [
        16050075
      ],
      "endInteger": 16050075,
      "startInteger": 16050074,
      "refseqId": "22",
      "assemblyId": "hg19"
    },
    "variation": {
      "variantType": "SNP",
      "alternateBases": "G",
      "referenceBases": "A",
      "location": {
        "interval": {
          "start": {
            "value": 16050074,
            "type": "Number"
          },
          "end": {
            "value": 16050075,
            "type": "Number"
          },
          "type": "SequenceInterval"
        },
        "type": "SequenceLocation",
        "sequence_id": "HGVSid:22:g.16050075A>G"
      }
    },
    "variantInternalId": "chr22_16050075_A_G",
    "identifiers": {
      "genomicHGVSId": "22:g.16050075A>G"
    }

Have I missed anything important from my query?


Regards,


David.


________________________________
From: Oriol López-Doriga ***@***.***>
Sent: Thursday, August 17, 2023 4:28 PM
To: EGA-archive/beacon2-ri-api
Cc: Croft, David; Author
Subject: [Extern] - Re: [EGA-archive/beacon2-ri-api] Variant queries using HGVS (Issue #175)


Hi David,

thank you for the explanation.

First of all, I have to tell you that Beacon specifications say that to search inside the g_variants endpoint you have to use request parameters other than filters, which are more used to find "clinical data", and the reason why ontologies are used. From this, then, alphanumeric and custom filters are used to find a "specific value" of this clinical data.

However, the "InternalVariantId" is not mapped for the request parameters because it is on purpose mapped in the specific /{id} endpoint, so I am afraid the only way to look for the "InternalVariantId" is by specifying it in the requested URI.
If you check the specifications here https://raw.githubusercontent.com/ga4gh-beacon/beacon-v2/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/framework/json/requests/examples-sections/requestParameters-example.json you will find the request parameters to be All the required fields to query any kind of variant (e.g. SNP, DUP,\netc.).".

Nonetheless, you can still get to this "InternalVariantId" by passing the exact request parameters that match it, like doing this type of POST request:

curl \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{
    "meta": {
        "apiVersion": "2.0"
    },
    "query": {
        "requestParameters": {
"Chromosome": "22",
    "alternateBases": "G" ,
    "referenceBases": "A" ,
"start": [ 16050075 ],
            "end": [ 16050075 ],
            "variantType": "SNP"
        },
        "filters": [],
        "includeResultsetResponses": "HIT",
        "pagination": {
            "skip": 0,
            "limit": 10
        },
        "testMode": false,
        "requestedGranularity": "record"
    }
}' \
  http://localhost:5050/api/g_variants


I hope this helps you.

Best,

Oriol
