### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by mustafahsyed** [EGA-archive/beacon2-ri-api#224]
```
Hi,

I have a dataset that should be accessible only by a group of users. I have added user in permissions/permissions.yml file as

`
user51578472:
- dataset123
`

But any user can access this dataset, looks like dataset is not restricted.

**Comment by costero-e** [comment]
Hi @mustafahsyed,

thank you very much for spotting this!

I just made a commit addressing this, you can find it in this PR: #234 

If you encounter any other issue, please tell me,

best,

Oriol

**Comment by mustafahsyed** [comment]
Hi,

Thanks for working on the issue. I am getting exception with the latest update in the highlighted code below

![image](https://github.com/EGA-archive/beacon2-ri-api/assets/47555094/6a3a57db-fd87-4e10-80d7-f65085eb861f)

Some debug messages in the screenshot below

![image](https://github.com/EGA-archive/beacon2-ri-api/assets/47555094/243294f6-c2e0-4e99-a862-b363e09db106)

Beacon is returning nothing

Please let me know if you need more information.

Thanks
Mustafa

**Comment by costero-e** [comment]
Hi @mustafahsyed !

thank you for the reporting. I am properly seeing returned my dataset records, so maybe is some information missing from dataset endpoint, as beacon is relating the ids by grabbing the info that is stored there.

Can you tell me if this is happening to you for all the datasets and what is the info you have in datasets endpoint?

Best,

Oriol

**Comment by mustafahsyed** [comment]
Hi Oriol,

It worked after properly formatting datasets

Thanks
Mustafa
