### ISSUE TITLE
Issues with count response 

### ISSUE THREAD

**Issue by gsfk** [EGA-archive/beacon2-ri-api#312]
Looking again at the reference implementation after a break of a couple years, thanks for all your work. I had a couple issues with count responses: 
- using GET, there appears to be no way to change the requestedGranularity parameter, `api/individuals?requested_granularity=count` and similar calls (camelCase, and with and without quotes around "count") all return 404.
- using POST, the `numTotalResults` value in the response summary is typically incorrect for a count response if the request happens to include pagination values. I offer up a fix [here](https://github.com/EGA-archive/beacon2-ri-api/pull/311).

**Comment by costero-e** [comment]
Hi @gsfk,
it's a pleasure to have you here again. Thanks for your feedback.
For the first question, I'm afraid that requested_granularity is not in the [specs](https://github.com/ga4gh-beacon/beacon-v2/blob/75850c3f19816ee05d4fd67d39811f9c5a6a8f29/models/src/beacon-v2-default-model/individuals/endpoints.yaml) as a get request parameter:
```
paths:
  /individuals:
    get:
      parameters:
        - $ref: '#/components/parameters/requestedSchema'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/includeResultsetResponses'
        - $ref: '#/components/parameters/filters'
``` 
For the second issue you are commenting, you are absolutely right, I reviewed your PR and I will accept it now, thank you very much!
Oriol

**Comment by gsfk** [comment]
Huh... I'm often surprised how far the GET and POST parts of the spec are. 

Thanks for this!

**Comment by costero-e** [comment]
You are welcome!
