### ISSUE TITLE
beacon2-ri-tools-v2:main image contains older version of ri-tools then latest

### ISSUE THREAD

**Issue by AlexCork1** [EGA-archive/beacon2-ri-api#361]
Docker compose file containes service beacon-ri-tools which is based on image: ghcr.io/ega-archive/beacon2-ri-tools-v2:main, which doesn't seem to be the newer version of beacon2-ri-tools-v2. Is that on purpose?

When I put the tag "latest" I get different image, which is notable in files genomicVariations_vcf.py (added function num_rows_in_vcf_files) and conf.py (removed line num_variants=10000000).

I start the docker file in both cases with command: docker-compose up -d --build

**Comment by costero-e** [comment]
Hi @AlexCork1, thank you for reporting this observation.

Indeed, by changing `ghcr.io/ega-archive/beacon2-ri-tools-v2:main` to `ghcr.io/ega-archive/beacon2-ri-tools-v2:latest` you are telling the docker to always look for the latest version, whatever which branch you are using, and check that you have it installed in your computer. 

On the other hand, to have only the latest main branch version you can execute directly the command `docker pull ghcr.io/ega-archive/beacon2-ri-tools-v2:main`. As your docker already found a main branch version, it didn't look for the latest version of the image without executing the docker pull command. 

As you suggested, I will change this to latest in the image source for the docker compose service, as it seems reasonable to do in an already stable tool.

Thank you very much,

Oriol
