### ISSUE TITLE
deploying beacon ri without docker?

### ISSUE THREAD

**Issue by albodrug** [EGA-archive/beacon2-ri-api#386]
Hello, 

Is is possible and is there a tutorial/doc on how to deploy the beacon ri without using docker? I have issues with access tokens on my university's network. I can deploy the ri just fine on my personal computer but the same steps do not work on my university cluster. 

Thanks for any tips!
Alex

**Comment by costero-e** [comment]
Hello @albodrug,

I'm afraid that right now there is no other possible set up of the repository without docker unless you use a virtual environment with python and the requirements installed in it.
If you opt for a virtual environment, you might need to tweak a bit the packages of the libraries, as some of them will only work for the OS environment we are providing in the docker set up.
If you'd like to have a different set up engine, you can suggest it here and we will explore the possibilities.

Thanks,

Oriol
