### ISSUE TITLE
Cannot download demo data file - Git LFS - Over Quota Limit 

### ISSUE THREAD

**Issue by amanjeev** [EGA-archive/beacon2-ri-api#75]
### Expected Behavior

When I clone the repo and run `git lfs install` in the repo, correct data file should be downloaded in beacon/deploy/db and running docker containers after that should launch the containers.

### Current Behavior

The file is not downloaded, beacon container exits and error on the console `gunzip: invalid magic`

```
Error downloading object: deploy/db/data.sql.gz (67b1c20): Smudge error: Error downloading 
deploy/db/data.sql.gz (67b1c20b4e2cbb4194037dcc26377515b01739e0f9eff5d50b874a6f24f6fa3d): 
batch response: This repository is over its data quota. Account responsible for LFS bandwidth 
should purchase more data packs to restore access.

This repository is over its data quota. Account responsible for LFS bandwidth should 
purchase more data packs to restore access.
```

### Possible Solution

Purchase more bandwidth please :sweat_smile:

**Comment by amanjeev** [comment]
Apologies, I should have searched before opening.  I see this comment now https://github.com/EGA-archive/beacon-2.x/issues/74#issuecomment-908258917

> As far as I know there is no plan to do that, and we should probably find another way to share the demo data.

Is there another way to get demo data?

**Comment by silverdaz** [comment]
Not at the moment.
We are working on a different approach: generate some fake demo data.
@sdelatorrep and @MrRobb can bring some light on it (in a few weeks).
Leaving the issue open so that, eventually, a discussion takes place here.
